export const ROUTE_PATHS = {
    HOME: '/',
    LOGIN: '/login',
    REGISTER: '/register',
    FORGOT_PASSWORD: '/forgot-password',
    EMAIL_CODE: '/email-code',
    EMAIL_SEND: '/email-sent',
    RESET_PASSWORD: '/reset-password',
    CONFIRM_PASSWORD: '/confirm-password',
    CREATE_PROPERTY: '/create-property',
    PARTNERS: '/partners',
    SEARCH: '/search',
    NOT_FOUND: '/*',
    PARTNERS_ANGEL: '/partners-angel',
    PROPERTY_MANAGEMENT: '/property-management',
    PARTNER_INTEGRATION_REQUEST: '/partner-integration-request',
    PROPERTY_DETAILS: '/property-details',
    APPOINTMENTS: '/appointments',
    REQUEST_APPOINTMENTS: '/request-appointments',
    USER_PROFILE: '/user-profile',
};
